### ISSUE TITLE
Get Function Return Value 

### ISSUE THREAD

**Issue by samuelgjekic** [theodo-group/LLPhant#106]
Hey, i have yet another question xD 

So i have been playing around with the library, working great but im wondering about the function calling.

Lets say i have this function in my class TestFunction:

```
public function getWeather()
{
    $weather = 'Sunny';
   echo $weather;
   return $weather; 
}
```
In the above code, everything works fine and the bot will trigger the **echo** statement. 

But lets say i want the bot to use the returned value, or atleast tell the user it has used the function.

Right now it will run the function, and the echo statement will show 'Sunny'. What approach would i take to make the bot reply with the returned value? Which is 'Sunny' in this case.  So for example bot reply would be **'Today its sunny outside!'**. But the bot would choose the words to use. 

Im using QuestionAnswer class to test this btw. I did notice the Message class has a static function called **functionResult**, where would this be stored?

I have been looking into the functions that make the function run, but im stuck on this atm.

Note: im testing on simple php website, nothing dynamic etc no javascript, i simply load the page to interact with the chatbot

**Comment by MaximeThoonsen** [comment]
Hey @samuelgjekic , you can use something like :
You can use `generateTextOrReturnFunctionCalled` so you can call manually the function yourself


```php
$stringOrFunctionInfo = $this->openAIChat->generateTextOrReturnFunctionCalled($prompt);
if ($stringOrFunctionInfo instanceof FunctionInfo) {
        // $toolResponse can be a very long string
        $toolResponse = FunctionRunner::run($stringOrFunctionInfo);
```

You can parse the FunctionInfo yourself and decide to do whatever you want with it before calling other functions.
You can have a look in AutoPHP folder, I use it a lot.

Did it help you?

**Comment by samuelgjekic** [comment]
Hey @MaximeThoonsen thanks for your fast reply! I found the generateTextOrReturnFunction yesterday, but i did not know i had to run the function when checking the instanceof, thank you it works perfect.
