### ISSUE TITLE
add Redis VectorStore

### ISSUE THREAD

**Issue by MaximeThoonsen** [theodo-group/LLPhant#11]

**Comment by Th0masso** [comment]
see https://github.com/theodo-group/LLPhant/pull/20

**Comment by Th0masso** [comment]
Hello @sachingk ! Redis is now available as a vector store ➔ [see version 0.2.6](https://packagist.org/packages/theodo-group/llphant#0.2.6)

**Comment by Th0masso** [comment]
You will need to install [Predis](https://github.com/predis/predis) to use it :)
