### ISSUE TITLE
Add similarity cosinus

### ISSUE THREAD

**Issue by ClicShopping** [theodo-group/LLPhant#117]
Hello,
It will be great if we can choose between euclidean and cosinus similarity in LLPhant\Embeddings\VectorStores\DistancesL2Utils.

This 2 approaches have advantage and disadvantage in function what we want to do.

Example :
```
 public function cosineSimilarity($vector1, $vector2): float|int
  {
    // Calculate the dot product of the two vectors
    $dotProduct = array_sum(array_map(function ($a, $b) {
      return $a * $b;
    }, $vector1, $vector2));

    // Calculate the magnitudes of each vector
    $magnitude1 = sqrt(array_sum(array_map(function ($a) {
      return $a * $a;
    }, $vector1)));

    $magnitude2 = sqrt(array_sum(array_map(function ($a) {
      return $a * $a;
    }, $vector2)));

    // Avoid division by zero
    if ($magnitude1 * $magnitude2 == 0) {
      return 0;
    }

    // Calculate the cosine similarity
    $cosineSimilarity = $dotProduct / ($magnitude1 * $magnitude2);

    return $cosineSimilarity;
  }
```

**Comment by MaximeThoonsen** [comment]
Yes I agree 👍️

**Comment by f-lombardo** [comment]
It seems an interesting proposal. @ClicShopping and @MaximeThoonsen what kind of design do you think it would be the best one? To pass the distance "name" in the `$additionalArguments` of the `VectorStoreBase::similaritySearch` method?

**Comment by MaximeThoonsen** [comment]
Hey @f-lombardo,
I would update the similaritySearch signature with an additionnal optional parameter "distance name" which can be a Enum

**Comment by MaximeThoonsen** [comment]
done
