### ISSUE TITLE
TextBreak  Error

### ISSUE THREAD

**Issue by pslxx** [theodo-group/LLPhant#123]
LLPhant\Embeddings\DataReader\FileDataReader::extractTextFromDocxNode(): Argument #1 ($section) must be of type PhpOffice\PhpWord\Element\Section|PhpOffice\PhpWord\Element\TextRun|PhpOffice\PhpWord\Element\Text, PhpOffice\PhpWord\Element\TextBreak given,

**Comment by MaximeThoonsen** [comment]
Hey @pslxx,
Thanks for spotting a bug. Can you give us a way of reproducing it: your php code + a word file that doesn't work?

**Comment by pslxx** [comment]
<img width="988" alt="image" src="https://github.com/theodo-group/LLPhant/assets/8417207/c0862f1b-6501-4a0a-b508-949d4398c4f9">
some docment (.docx) has TextBreak tags ,so ....
