### ISSUE TITLE
Question from coherence between embbeding from file or database document insertion/update

### ISSUE THREAD

**Issue by ClicShopping** [theodo-group/LLPhant#136]
Hello,
I would know if this condition give the same result to convert a text in embedding. I am not sure the result is the same because the threatment is different if the text come from file or a database text.

```
$filePath = /var./...../ ' . $new_dir . $file_upload; //$document_description

first upload / create the embedding document
      if(is_file($filePath)) {
        $reader = new FileDataReader($filePath, PlaceEntity::class);
        $documents = $reader->getDocuments();
        $splitDocuments = DocumentSplitter::splitDocuments($documents, 500);
        $formattedDocuments = EmbeddingFormatter::formatEmbeddings($splitDocuments);
        $embeddingGenerator = new OpenAI3SmallEmbeddingGenerator();
        $embeddedDocuments = $embeddingGenerator->embedDocuments($formattedDocuments);
print_r(embeddedDocuments); ====> the result when you insert the document
      } else {
        //update a text and convert in embedding

        $embeddingGenerator = new OpenAI3LargeEmbeddingGenerator();
        $embedded = $embeddingGenerator->embedText($document_description);// embedding
//        $document = new Document();
//       $document->content = $job_description;
//        $document->embedding = $embedded;

        print_r($embedded);
      }
```
      
      there are differences between the condition and can influence the result.
      - the first is the `splitDocuments` have inside the update
      - the second is `formatEmbeddings` we do not have also.
      
      Maybe I forget something or I do not use something correct but between an update and insert, we must have the same coherence. How to you that  and resolve this point ?
      
      Than you.

**Comment by bernard-ng** [comment]
Hello @ClicShopping 

You'll notice that the framework doesn't really take this use case into account, as you're not directly saving the uploaded document but rather the splits of the uploaded document, which makes it difficult to find the initial (entier) document to update the embeddings.

what you can do is separate your “embeddings” documents from the uploaded documents and create a relationship between each embedding and associated uploaded document, so that if an associated uploaded document is updated you can simply delete all the associated embeddings 

and recreate embeddings for the updated document, by repeating the same process

**Comment by ClicShopping** [comment]
Yes I know that. but in my case, I manage job description  (but it could be product description, a documentation .....) for example and the text can be change anytime. To upload a document is relevant, but in my case the user can use a chatbot, and copy paste to integrate the information inside the job description before to continue the process (that s example).
The process is like to upload a document, just you do not upload because you have the text.
I do not know if @MaximeThoonsen could be interested.

**Comment by bernard-ng** [comment]
@ClicShopping I see, I think you have two solutions in this case, first you use an EmbeddingGenerator with a wider context window, which could avoid splitting up your description and thus make them easier to update

the second solution is to associate each job description with one or more embeddings (OneToMany), keeping the job reference (job_id) in the embeddings table. If the description is updated, we delete the old embeddings and create new ones based on the new description (and obviously splitting and formatting them too).

**Comment by ClicShopping** [comment]
@bernard-ng If the description is updated, we delete the old embeddings and create new ones based on the new description (and obviously splitting and formatting them too).
Yes it s exact, this the way, if you have an idea to integrate that I am open. 
the document must be splitted and maybe formated as show above inside else condition but  $documents must respect an array format.
```
 $splitDocuments = DocumentSplitter::splitDocuments($documents, 500);
 $formattedDocuments = EmbeddingFormatter::formatEmbeddings($splitDocuments);
```

**Comment by bernard-ng** [comment]
I assume you're using postgres as a VectorStore (with doctrine) you can add properties by extending the basic Document class


```php
// your entity
JobDescriptionDocument extends Document {
    public Job $job // ManyToOne relationship
}
```

```php
// in your controller

$document = new JobDescriptionDocument();
$document->job = $job
$document->content = $job->getDescription();
$document->sourceName = $job->getName();
$document->sourceType = "job description";

$splitDocuments = DocumentSplitter::splitDocument($document, 500);
$formattedDocuments = EmbeddingFormatter::formatEmbeddings($splitDocuments);
$embeddingGenerator = new OpenAI3SmallEmbeddingGenerator();
$embeddedDocuments = $embeddingGenerator->embedDocuments($formattedDocuments);
```

**Comment by ClicShopping** [comment]
thank you, give me the way to resolve that
