### ISSUE TITLE
generateChat() instead of generateChatStream() under the QuestionAnswering

### ISSUE THREAD

**Issue by himinat** [theodo-group/LLPhant#137]
Hello,
is there any reason QA->answerQuestionFromChat() is using generateChatStream() instead of generateChat()?
cant find any way how to use QA without streamed response, but the code is actually there...

is it acceptable if ill push a pull request with a new method in QA class that returns 
`$this->openAIChat->generateChat` instead of `$this->openAIChat->generateChatStream`?

**Comment by samuelgjekic** [comment]
I noticed this aswell my guess would be that the question answering class is a class that was made as an example on how semantic search works. 

I usually change the last 
 ```
return $this->chat->generateChatStream($messages);

```

To match the generateChat in my projects. I think adding this to the question answering class is a good idea for the library. 

We will see what @MaximeThoonsen  thinks 🙂 but i think he appreciates all contributions.

**Comment by MaximeThoonsen** [comment]
Hey @himinat and @samuelgjekic,

Yes I wanted to keep it simple and people use more the chat with streaming but you can add a method in QA that is not using the streaming for sure!
