### ISSUE TITLE
Adding chunk overlapping to document splitting

### ISSUE THREAD

**Issue by mikelmao** [theodo-group/LLPhant#138]
I propose adding a new parameter `$overlap = 0` to the `splitDocument()` method in `DocumentSplitter` and making the function consider the specified number of characters in overlapping the previous chunk in to the current chunk. 

This would allow for the chunks being created to overlap a specified amount of characters to optimize for RAG use cases

**Comment by MaximeThoonsen** [comment]
Hey @mikelmao, yes this is a behavior from Langchain. I agree. Do you want to contribute on this one?

**Comment by synio-wesley** [comment]
I am also missing this functionality. Looks like I would have to create it myself?
