### ISSUE TITLE
PlaceEntity not found

### ISSUE THREAD

**Issue by ClicShopping** [theodo-group/LLPhant#140]
When I tried to upload a pdf document, I have a php error

PHP Fatal error:  Uncaught Error: Class "..........\PlaceEntity" not found in ............/vendor/theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php:120

$reader = new FileDataReader($filePath, PlaceEntity::class);
$documents = $reader->getDocuments();

I tried to look inside the librairies PlaceEntity not exist.

**Comment by ClicShopping** [comment]
It seems the document is not updated
tried this : $reader = new FileDataReader($filePath); 
works fine

**Comment by f-lombardo** [comment]
I think that documentation is a bit misleading here. I'll try to improve it a bit
