### ISSUE TITLE
Enable auto-update on packagist

### ISSUE THREAD

**Issue by thomasbeaujean** [theodo-group/LLPhant#149]
Hi @MaximeThoonsen,

I see on packagist that the main of the repo is not in sync with packagist:
https://packagist.org/packages/theodo-group/llphant#dev-main

Could you please enable the auto update ?

**Comment by fballiano** [comment]
latest verion on packagist is not in sync with github, maybe it was solved?

**Comment by f-lombardo** [comment]
So the problem seems solved now?

**Comment by fballiano** [comment]
I guess so, unless it was manually synced
