### ISSUE TITLE
Mistral embedding rate limit exceeded

### ISSUE THREAD

**Issue by cirolaferrara** [theodo-group/LLPhant#159]
```
$config = new OpenAIConfig();
$chat = new MistralAIChat($config);
$embeddingGenerator = new MistralEmbeddingGenerator();

$dataReader = new FileDataReader(__DIR__.'/myfile.pdf');
$documents = $dataReader->getDocuments();
$splittedDocuments = DocumentSplitter::splitDocuments($documents, 3072);
$formattedDocuments = EmbeddingFormatter::formatEmbeddings($splittedDocuments);
$embeddedDocuments = $embeddingGenerator->embedDocuments($formattedDocuments);
```
returns 

> PHP Warning:  Undefined array key "data" in llphant\vendor\openai-php\client\src\Responses\Embeddings\CreateResponse.php on line 49

According to [Mistral AI limits](https://console.mistral.ai/billing/limits/), we can do 1 request per second. In the embedDocuments function, there is a loop over Documents that calls embedDocument. embedDocument calls embedText that calls LLM to do the work. This is process is too fast.

**Comment by cirolaferrara** [comment]
This is the test

```
<?php

declare(strict_types=1);

namespace Tests\Integration\Embeddings\EmbeddingGenerator;

use LLPhant\Embeddings\EmbeddingGenerator\Mistral\MistralEmbeddingGenerator;

it('can embed some stuff with pause', function () {
    $llm = new MistralEmbeddingGenerator();
    for($i=0; $i<=5; $i++) {
        sleep(2);
        $lastEmbedding = $llm->embedText('This number is '.$i);
    }
    expect($lastEmbedding[0])->toBeFloat();
});

it('can embed some stuff', function () {
    $llm = new MistralEmbeddingGenerator();
    for($i=0; $i<=5; $i++) {
        $lastEmbedding = $llm->embedText('This number is '.$i);
    }
    expect($lastEmbedding[0])->toBeFloat();
});
```

**Comment by f-lombardo** [comment]
The problem is real, and I think it's not limited to Mistral, but probably could happen using OpenAI too. Unfortunately the solution isn't trivial, since rate limits depend on your subscription type, so we can't wait for a fixed amount of time.
A possible workaround could involve batches: https://github.com/openai-php/client?tab=readme-ov-file#batches-resource

I think that another solution could be to intercept HTTP code 429, but at the moment I can't understand how. @MaximeThoonsen , do you have any idea?

**Comment by cirolaferrara** [comment]
@f-lombardo  `embedText` into `src/Embeddings/EmbeddingGenerator/EmbeddingGeneratorInterface.php` should accept array. Not only a string.

See [openai api docs](https://platform.openai.com/docs/api-reference/embeddings/create) and [mistral api docs](https://docs.mistral.ai/api/#operation/createEmbedding).

[ollama](https://github.com/ollama/ollama/blob/main/docs/api.md) accepts only a string.

**Comment by MaximeThoonsen** [comment]
hey @cirolaferrara you are right, we can batch now: https://docs.mistral.ai/capabilities/embeddings/

So we could send a batch of something like ~50 embedding (maybe even more).
Do you want to suggest a change for this one?

**Comment by MaximeThoonsen** [comment]
I had a look at the code from openai-php, I didn't see how we could batch. So :

- either we make a PR on openai-php project's  
- or we use another client to make the call 

what do you think?

**Comment by MaximeThoonsen** [comment]
I went for using guzzle.
Does it work for you @cirolaferrara ?

**Comment by cirolaferrara** [comment]
In these days I am doing some testing. What do you think about using a dedicated client for each LLM?
[Mistral](https://github.com/HelgeSverre/mistral),  [Ollama](https://github.com/evowareio/ollama-php) [Openai](https://github.com/openai-php/client)?

**Comment by MaximeThoonsen** [comment]
My goal is to keep everything as simple as possible. So I'd prefer if we could avoid that.
But if we need it, no problem

**Comment by bytestream** [comment]
@MaximeThoonsen would you accept some kind of static class which keeps track of the `X-RateLimit-*` headers, and then users of the library can easily access that information and act upon it. I only use OpenAI but I assume each LLM exposes similar headers?

**Comment by MaximeThoonsen** [comment]
hey @bytestream sorry I missed your comment. yes sure.

@RobinDev it's another thing. The batch API is for async call where you get the answer within 24 hours
