### ISSUE TITLE
Array to string conversion theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php:108

### ISSUE THREAD

**Issue by aram99777** [theodo-group/LLPhant#160]
when we use FileDataReader class and call getDocuments function and  If there are links in the docx file then this error is thrown
Array to string conversion theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php:108

```
#0 ---/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 ---/vendor/theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php(108): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 ---/vendor/theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php(111): LLPhant\\Embeddings\\DataReader\\FileDataReader->extractTextFromDocxNode()
#3 ---/vendor/theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php(95): LLPhant\\Embeddings\\DataReader\\FileDataReader->extractTextFromDocxNode()
#4 ---/vendor/theodo-group/llphant/src/Embeddings/DataReader/FileDataReader.php(38): LLPhant\\Embeddings\\DataReader\\FileDataReader->getContentFromFile()
```

` $dataReader = new FileDataReader($path);`
`  $documents = $dataReader->getDocuments();`

**Comment by aram99777** [comment]
[New Microsoft Office Word Document (1).docx](https://github.com/user-attachments/files/16012335/New.Microsoft.Office.Word.Document.1.docx)
example this file

**Comment by cirolaferrara** [comment]
#163 should fix it

**Comment by MaximeThoonsen** [comment]
Hey @aram99777 , @f-lombardo pushed a fix, can you test it?

**Comment by f-lombardo** [comment]
I tested the new version of LLPhant with the provided file and it seems working. I guess this issue can be closed now
