### ISSUE TITLE
Can not add an embedding with the .docx format.

### ISSUE THREAD

**Issue by Vardan9898** [theodo-group/LLPhant#198]
ErrorException: Undefined array key "data" in /home/.../vendor/theodo-group/llphant/src/Embeddings/EmbeddingGenerator/OpenAI/AbstractOpenAIEmbeddingGenerator.php:117

[sample1.docx](https://github.com/user-attachments/files/16573509/sample1.docx)

Code:

$reader = new FileDataReader($filePath, PlaceEntity::class);
        $documents = $reader->getDocuments();
        $splittedDocuments = DocumentSplitter::splitDocuments($documents, 1024, "\n");
        $formattedDocuments = EmbeddingFormatter::formatEmbeddings($splittedDocuments);
        $embededDocuments = $embeddingGenerator->embedDocuments($formattedDocuments);
        
 I use OpenAI3SmallEmbeddingGenerator()

**Comment by Vardan9898** [comment]
JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in /home/.../vendor/theodo-group/llphant/src/Embeddings/EmbeddingGenerator/OpenAI/AbstractOpenAIEmbeddingGenerator.php:111

Another error when uploading pdf file

**Comment by f-lombardo** [comment]
> JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in /home/.../vendor/theodo-group/llphant/src/Embeddings/EmbeddingGenerator/OpenAI/AbstractOpenAIEmbeddingGenerator.php:111
> 
> Another error when uploading pdf file

I think that this is an error related to the smalot/pdfparser library used for parsing PDF. One option would be to open an issue there. Anyway, could you please provide a sample PDF file that generates this issue?
Thank you.

**Comment by f-lombardo** [comment]
> ErrorException: Undefined array key "data" in /home/.../vendor/theodo-group/llphant/src/Embeddings/EmbeddingGenerator/OpenAI/AbstractOpenAIEmbeddingGenerator.php:117

I created a PR to try to fix this issue: https://github.com/theodo-group/LLPhant/pull/200

Please check if it works for you

**Comment by Vardan9898** [comment]
Seems it's fixed for docx, but could you please check with attached pdf file? I get an
[The-No-Funnel-Strategy.pdf](https://github.com/user-attachments/files/16590197/The-No-Funnel-Strategy.pdf)
 error:

JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in /home/.../vendor/theodo-group/llphant/src/Embeddings/EmbeddingGenerator/OpenAI/AbstractOpenAIEmbeddingGenerator.php:111

**Comment by f-lombardo** [comment]
> Seems it's fixed for docx, but could you please check with attached pdf file? 

I pushed a new commit to the previous PR. Can you please check if it works for you?

**Comment by Vardan9898** [comment]
It works. Thank you.
