### ISSUE TITLE
TypeError: LLPhant\Embeddings\DataReader\DocxReader::toString()

### ISSUE THREAD

**Issue by Vardan9898** [theodo-group/LLPhant#209]
Hello everyone,

I encountered an error while trying to upload a DOCX file. Below is the error message I received. Does anyone have any suggestions on how to fix this?

Error:
TypeError: LLPhant\Embeddings\DataReader\DocxReader::toString(): Argument #1 ($text) must be of type array|string|null, PhpOffice\PhpWord\Element\TextRun given, called in /home/vardan/projects/aminos/vendor/theodo-group/llphant/src/Embeddings/DataReader/DocxReader.php on line 29 and defined in /home/vardan/projects/aminos/vendor/theodo-group/llphant/src/Embeddings/DataReader/DocxReader.php:55
Stack trace:
#0 /home/vardan/projects/aminos/vendor/theodo-group/llphant/src/Embeddings/DataReader/DocxReader.php(29): 

[BUSI 1815 Introduction to Entrepreneurship.docx](https://github.com/user-attachments/files/16715825/BUSI.1815.Introduction.to.Entrepreneurship.docx)

**Comment by f-lombardo** [comment]
@Vardan9898 Please check if this PR fixes your problem: https://github.com/theodo-group/LLPhant/pull/211

**Comment by Vardan9898** [comment]
@f-lombardo Yes, it fixes the issue. Thanks! I’ll wait for it to be merged.

**Comment by MaximeThoonsen** [comment]
@Vardan9898 it is merged. Thanks guys !
