### ISSUE TITLE
add ElasticSearch as Vector Store

### ISSUE THREAD

**Issue by Th0masso** [theodo-group/LLPhant#23]

**Comment by Th0masso** [comment]
see PR https://github.com/theodo-group/LLPhant/pull/24

**Comment by andrefrcastro** [comment]
Also redis support with [phpredis](https://github.com/phpredis/phpredis) please

**Comment by simpleenigma** [comment]
Would this also work with AWS OpenSearch? If not, is it possible to get an AWS OpenSearch vector store?

**Comment by andrefrcastro** [comment]
Support for AWS OpenSearch would be awesome too

**Comment by MaximeThoonsen** [comment]
Hey @simpleenigma and @andrefrcastro . Can you test if it works or not and tell me?
If it doesn't work, we will add support

**Comment by Th0masso** [comment]
@andrefrcastro i created an [issue](https://github.com/theodo-group/LLPhant/issues/34) for you :)
