### ISSUE TITLE
Support for structured_output

### ISSUE THREAD

**Issue by yellow1912** [theodo-group/LLPhant#230]
I wonder if it is possible to support structured_output from OpenAI

https://openai.com/index/introducing-structured-outputs-in-the-api/

It's very useful to work with json structured out for example.

**Comment by prykris** [comment]
`OpenAIChat::setModelOption('response_format', ['type' => 'json_schema']);`

That is all you need. You just need to craft your own JSON schema.

**Comment by yellow1912** [comment]
thank you for your help, I got it working.
