### ISSUE TITLE
How to let the AI continue the conversation after calling function 

### ISSUE THREAD

**Issue by samuelgjekic** [theodo-group/LLPhant#251]
So basically, if i use the return function called method, the AI will respond with the value that got returned from the function. 

Is there a way to make it so the AI answers instead? 

Example 

*Me: Hi!

*AI: hi there!

*Save my email email@mail

*AI* ...... < I want the AI to continue the conversation, for example say "i have now added your email to the list" 

For now, all it does is show me the returned value from the function, the ai is not responding on its own i would have to ask something again for it to talk

Im sorry if this was complicated , i am on my phone just curious to see how other people do when they want to achieve this ?.

**Comment by f-lombardo** [comment]
Hi @samuelgjekic , it's an interesting question.
`generateChat` and `generateText`  work that way, i.e. they call the provided functions if Anthropic engine requires that and they provide the answer to the user. See for example: 
https://github.com/theodo-group/LLPhant/blob/121e6dba0f2f824d2fd707d19c219fe2af777bd4/tests/Integration/Chat/AnthropicChatTest.php#L32 
or https://github.com/theodo-group/LLPhant/blob/121e6dba0f2f824d2fd707d19c219fe2af777bd4/tests/Integration/Chat/AnthropicChatTest.php#L57
or https://github.com/theodo-group/LLPhant/blob/121e6dba0f2f824d2fd707d19c219fe2af777bd4/tests/Integration/Chat/OpenAIChatTest.php#L95
Note that `AnthropicChat` can also handle nested function calls:
https://github.com/theodo-group/LLPhant/blob/121e6dba0f2f824d2fd707d19c219fe2af777bd4/src/Chat/AnthropicChat.php#L99
The `generateChatOrReturnFunctionCalled` is designed to manually handle this loop:  you have to call functions as a result of AI request and then manually provide the results to the engine again.
See for example https://github.com/theodo-group/LLPhant/blob/121e6dba0f2f824d2fd707d19c219fe2af777bd4/tests/Integration/Chat/OpenAIChatTest.php#L112
I think that @MaximeThoonsen could give a better explanation, maybe correcting me if I missed anything.

**Comment by MaximeThoonsen** [comment]
@samuelgjekic yes you need to manually call the LLM again with the result of the function to get the conversation goes on. There are so many thing that you can do with function calling other than just returning the result directly to the LLM that I think it's better to keep it manual. 
Hope it helps

**Comment by samuelgjekic** [comment]
> @samuelgjekic yes you need to manually call the LLM again with the result of the function to get the conversation goes on. There are so many thing that you can do with function calling other than just returning the result directly to the LLM that I think it's better to keep it manual. Hope it helps

Yes, i ended up doing it this way after reading @f-lombardo answer, appriciate the response and yeah i understand. You can close this as solved.
