### ISSUE TITLE
Using 'Function' as namespace seems to be causing error

### ISSUE THREAD

**Issue by onlinesid** [theodo-group/LLPhant#31]
PHP 8.2 Win 11 WSL 2.0 Ubuntu on VSCode

![image](https://github.com/theodo-group/LLPhant/assets/99542/7c369bc3-efeb-4659-9424-8838837597ce)

Maybe we should not use 'Function' as namespace in PHP?

**Comment by MaximeThoonsen** [comment]
Good point @onlinesid . I fixed it in the last version

**Comment by onlinesid** [comment]
Thank you for the super quick fix on this issue! The package is still quite unstable though, there was another error but I'll check again maybe it's already fixed now, if not I'll submit an issue. Cheers

**Comment by MaximeThoonsen** [comment]
Can you tell me your new error so I can help?

**Comment by onlinesid** [comment]
Hi @MaximeThoonsen I just checked again and the syntax error disappeared, maybe it was just vscode cache, so all good right now I'll carry on, thank you so much for the quick response much appreciated
