### ISSUE TITLE
add PhpRedis as a Vector Store

### ISSUE THREAD

**Issue by Th0masso** [theodo-group/LLPhant#34]
It is already possible to store data using Redis with Predis. 
- PhpRedis have better performances, it is 6 times faster if we refer to [this article from 2019](https://akalongman.medium.com/phpredis-vs-predis-comparison-on-real-production-data-a819b48cbadb).
- PhpRedis is harder to install, and the installations steps depends on the OS

**Comment by MaximeThoonsen** [comment]
Done

**Comment by synio-wesley** [comment]
@MaximeThoonsen Sorry, but I don't see PhpRedis yet? I only see predis? PhpRedis would be much faster and I could easily use the native PhpRedis in Laravel that way as well without requiring an additional predis client.
