### ISSUE TITLE
How to use it? 😅

### ISSUE THREAD

**Issue by brtsos** [theodo-group/LLPhant#42]
Hi 🙂

Your work is amazing! I love it ❤️

I have a question. We have the option to inquire from OpenAI about something, or we can utilize our own data. 
Is it possible to combine both approaches?

Currently, if I pose a question to QuestionAnswering->answerQuestion, for instance, "How to make a backup on Linux", and I don't have any information on this subject in my database, I receive the response "I don't know the answer."

Thanks 🙏

**Comment by MaximeThoonsen** [comment]
Hey @brtsos ,

Thanks for your kind words! 
Yes this is not ideal as an answer. You can change the system message (stored in $systemMessageTemplate) of the QuestionAnswer object. For now it is `"Use the following pieces of context to answer the question of the user. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\n{context}."`.
You could try something like `""Use your knowledge or the following pieces of context to answer the question of the user. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\n{context}."`

It will solve your problem. Tell me if it worked =)

**Comment by brtsos** [comment]
omg, omg omg! I love your answer! Can I donate this project? :D

**Comment by MaximeThoonsen** [comment]
We don't need donation for the moment but if you want to help us:
- any contribution or feedbacks like you did are welcome
- spreading the word about the repository on X/Twitter or Linkedin
- if you know some companies that need GenAI expertise, you can ping us

Anyway tanhks for suggesting that!
