### ISSUE TITLE
Small issue with Document class.

### ISSUE THREAD

**Issue by BoweFrankema** [theodo-group/LLPhant#44]
I had issues with the following error:

Typed property LLPhant\Embeddings\Document::$hash must not be accessed before initialization

After a lot of debugging and help from ChatGTP 4 I found the following:

_"The error message you're encountering, "Typed property LLPhant\Embeddings\Document::$hash must not be accessed before initialization," is related to the initialization of the typed property $hash in the LLPhant\Embeddings\Document class.

In PHP 7.4 and later, when you define a typed property, it must be initialized either at the point of declaration or in the class constructor before it can be accessed. The error message indicates that the $hash property is being accessed before it has been initialized.

To resolve this issue, you should ensure that the $hash property is initialized before it is accessed. You can do this by providing a default value or initializing it in the constructor of the Document class. Here's an example of how you can initialize it with a default value:"_

I fixed the issue by updating in **src/Embeddings/Document.php**

public string $hash;

to

**public string $hash = '';**

---

Note: Encountered on PHP 8.2 :-) Everything is working now!

**Comment by MaximeThoonsen** [comment]
Hey @BoweFrankema,
Thanks for the feedback! I changed the code with your fix, the last version (0.2.11) has it.
Tell me if it's not working
