### ISSUE TITLE
Create a data reader for Notion

### ISSUE THREAD

**Issue by MaximeThoonsen** [theodo-group/LLPhant#5]

**Comment by f-lombardo** [comment]
Hi, I'd like to try to handle this issue as my first contribution. Could you give some more context about this?

**Comment by MaximeThoonsen** [comment]
Hey @f-lombardo,
Thanks for this. The goal is to create a NotionDataReader class that loads the .md files of a notion export and creates Documents out of it. You can also named it MarkdownDataReader as it should mainly be a class that read correctly information from a Markdown file.

You can have a look here for the JS version : https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/fs/notion.ts for a minimal version of it.

Does it help?

**Comment by f-lombardo** [comment]
Hi @MaximeThoonsen , thank you very much for the infos. I hope to send you a PR soon.

**Comment by f-lombardo** [comment]
Hi @MaximeThoonsen , what's  your opinion about the continuation of this issue? Do you think that https://github.com/theodo-group/LLPhant/pull/129 will be enough, or that we should create a specific NotionReader?

**Comment by MaximeThoonsen** [comment]
done
