### ISSUE TITLE
Error while using function

### ISSUE THREAD

**Issue by absolutemadla8** [theodo-group/LLPhant#52]
This is my code that gets list of products from database 

`LLPhant\Chat\FunctionInfo\TypeMapper::mapPhpTypeToJsonSchemaType(): Argument #1 ($reflectionType) must be of type ReflectionNamedType, null given`

My code is

```
$functionInfo = FunctionBuilder::buildFunctionInfo(new Products(), 'indexProducts');
                $this->chat->addFunction($functionInfo);
                $response = $this->chat->generateTextOrReturnFunctionCalled($prompt);
```

**Comment by MaximeThoonsen** [comment]
Hey @absolutemadla8,

Can you give me the signature of your method ?

**Comment by MaximeThoonsen** [comment]
Maybe you didn't put a type on one of your function parameter.

Working example: public function sendMail(**string** $subject, **string** $body, string $email)

**Comment by MaximeThoonsen** [comment]
You can describe manually your method if you prefer:
```php
$subject = new Parameter('subject', 'string', 'the subject of the mail');
$body = new Parameter('body', 'string', 'the body of the mail');
$email = new Parameter('email', 'string', 'the email address');

$function = new FunctionInfo(
    'sendMail',
    new MailerExample(),
    'send a mail',
    [$subject, $body, $email]
);
```

**Comment by absolutemadla8** [comment]
What I'm trying to do is when a user asks about available products

**Comment by MaximeThoonsen** [comment]
did you try what I suggested and still got the error ?

**Comment by absolutemadla8** [comment]
> did you try what I suggested and still got the error ?

Hey, its working now. I forgot to put type on one of my parameters. 
However I'm confused how to differentiate between arguments that I want to pass internally and arguments that I want ask the user. Such as products connected to a store_id has to be passed in internally by my logic.

**Comment by absolutemadla8** [comment]
Actually better question would be how can I create my own tool using this library? 
This would be really helpful. Thanks!

**Comment by absolutemadla8** [comment]
Just one last thing, while the function is being successfully executed I am unable to pass the response to GPT. Therefore the function is executed but there is not message sent to the user with the data that was given as a response by the function.

**Comment by MaximeThoonsen** [comment]
Hey,
> However I'm confused how to differentiate between arguments that I want to pass internally and arguments that I want ask the user
OpenAI needs the to know what arguments you need to call your function. If you need some inputs from your user, you have many classic ways of getting it. If you are in a chatbot context , you can put in the prompt that at some point you'll need to get a data from the user and then let the conversation happen. At some point the LLM will ask the user the question et you'll need to parse it from the user response.

>Just one last thing, while the function is being successfully executed I am unable to pass the response to GPT. Therefore the function is executed but there is not message sent to the user with the data that was given as a response by the function.

See this [PR](https://github.com/theodo-group/LLPhant/pull/51) to have an example on how to pass the response to GPT.

`$response = $this->chat->generateTextOrReturnFunctionCalled($prompt);` => you have the response from the function, you can send it back to the user in a raw way. Or you can call GPT with the answer like in the PR and wait for GPT answer. Or you can call GPT with a custom prompt dedicated to what happen after your function is called.

Does this help you?

**Comment by absolutemadla8** [comment]
Hey, 
I did help, thanks a lot. 
I have another question. I'm trying to embed a document but it is returning an array whereas it should return a vector. How can I resolve this issue?

**Comment by MaximeThoonsen** [comment]
The array is the PHP representation of the vector. Where in your code does it create you a problem?

**Comment by absolutemadla8** [comment]
It creates an Issue when I'm saving it in elastic search. It returns `Failed to parse object: expecting token of type [VALUE_NUMBER] but found [START_ARRAY]`

When I log the response of
```
$embeddingGenerator = new OpenAIEmbeddingGenerator();
            $embedding = $embeddingGenerator->embedDocuments($formattedDocuments);
            \Log::info("embedding" . json_encode($embedding));
```

it returns "local.INFO: embedding[{"content":"[{\"id\":8719676342565,\"title\":\"Gift Card\...., embedding:[0.12232]".

the structure seems to be 
[{
    "content":[{
        "embedding":[]
        "sourceType":"files",
        "sourceName":"\/Users\/mukulsharma\/Documents\/withoctober\/storage\/app\/temp\/places_1699270507.txt",
        "hash":"b2306a679edeb05ad3e4aea1791ad12756a889dd0e8656844188d6e6a004a8ad",
        "chunkNumber":0
    }],
    "content":[{
        "embedding":[]
        "sourceType":"files",
        "sourceName":"\/Users\/mukulsharma\/Documents\/withoctober\/storage\/app\/temp\/places_1699270507.txt",
        "hash":"b2306a679edeb05ad3e4aea1791ad12756a889dd0e8656844188d6e6a004a8ad",
        "chunkNumber":0
    }],
}]

**Comment by Th0masso** [comment]
Hello @absolutemadla8 ! Can you show me how you try to store the embedding the ES ?
You probably want to use the ElasticsearchVectorStore (see [ElasticsearchVectorStoreTest.php](https://github.com/theodo-group/LLPhant/tree/7431c873be916d6ad32022cceed8e27925343fe6/tests/Integration/Embeddings/VectorStores/Elasticsearch)).

If you want to store the embeddings without using our VectorStore, you should use "[Dense vector](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html)" type in ES.

**Comment by MaximeThoonsen** [comment]
No news I'm closing this for now
