### ISSUE TITLE
maria db vector inside  Text 

### ISSUE THREAD

**Issue by ClicShopping** [theodo-group/LLPhant#70]
Hello,
Sorry it s not a issue but I do not know where I can ask a question.
inside the application I store the vector (ada model) inside my maria db  database.
I can use that to evaluate a cosinus.
but if I want to use LLphant, with this approach, Can I do that ?
Tku

**Comment by MaximeThoonsen** [comment]
Hey @ClicShopping ,

So you store the embeddings of your model inside a maria db database.
Now you want to perform a semantics search with cosinus as a distance. 
It seems, you can't do it in Maria for now: https://mariadb.org/generative-ai-start/
So you should find another vector store that will also help you do the search with the cosinus.

LLPhant can help you create a script that 1) create the embeddings 2) store them in a vector store 3) make it easy to search in the vector search.

Does it help you?

**Comment by ClicShopping** [comment]
Thank but it's alpha in this moment. I hope the release will be soon.

I stock the vector ada model inside a longtext fied in this moment and I calcul the cosinus via the mathematics formula, I do not segment the text as you do inside your example code. Is it a problem with my approach because I have an error ? Maybe I forget something !!!

ex :

```
PHP Fatal error:  Uncaught TypeError: LLPhant\Query\SemanticSearch\QuestionAnswering::__construct(): Argument #1 ($vectorStoreBase) must be of type LLPhant\Embeddings\VectorStores\VectorStoreBase, array given,

     foreach ($resume_array as $resume) {
          $databaseVector = json_decode($resume['embedding'], true); // array(1536) { [0] => double(-0.02406735) [1] => double(0.00045954686) [
          $similarity = Vector::getCosineSimilarity($embedding_search, $databaseVector);

          if ($similarity >= $threshold) {
            $results[] = [
              'id' => $resume['id'],
              'embedding' => $resume['embedding'],
              'similarity' => $similarity,
            ];

//LLphant   -> tests/Integration/Query/Embeddings/QAQueryTest.php        
            $qa = new QuestionAnswering(
              $databaseVector,
              $embedding_search,
              new OpenAIChat()
            );
          }

          $answer = $qa->answerQuestion('Donne moi le nom des cv  experts en ecommerce');
          var_dump($answer);
          expect($answer)->toContain('cheese');
          }
      }    
```
