### ISSUE TITLE
how to use stream response?

### ISSUE THREAD

**Issue by daunt** [theodo-group/LLPhant#78]
i having problem with that
`return (new OpenAIChat($config))->generateStreamOfText('good morning');`
![image](https://github.com/theodo-group/LLPhant/assets/12959799/5bb5eea8-2b6a-4d13-a47a-12d5e89311d5)

but it runs fine when I use openai library directly
`$stream = $chat->chat()->createStreamed([
            'model' => 'gpt-3.5-turbo',
            'messages' => [
                ['role' => 'user', 'content' => 'good morning'],
            ],
        ]);`
`foreach ($stream as $response) {
            echo json_encode($response);
        }`
![image](https://github.com/theodo-group/LLPhant/assets/12959799/8c22fbad-6349-4fe1-b6cd-c8542345a675)

**Comment by MaximeThoonsen** [comment]
Hey @daunt, which version of LLPhant do you use?

**Comment by daunt** [comment]
> Hey @daunt, which version of LLPhant do you use?

![image](https://github.com/theodo-group/LLPhant/assets/12959799/76089074-d213-4ce9-a8d6-ba4de916b6b5)

last version of repo

![image](https://github.com/theodo-group/LLPhant/assets/12959799/8e115228-ad62-40a0-85d3-cfbb5020eae3)

i changed the code a little and it worked

**Comment by MaximeThoonsen** [comment]
OK. @ezimuel it seems the change you did for streaming did not work or maybe there is something more to do to make it work?

**Comment by ezimuel** [comment]
We need to reproduce the issue with a test. I'll work on it.

**Comment by daunt** [comment]
Thank you for attention..
by the way, can I contribute to add TEI by HF or can you provide it too?
source : [TEI](https://github.com/huggingface/text-embeddings-inference)

**Comment by ezimuel** [comment]
@daunt You are more than welcome to contribute with a `TEIChat` and `TEIConfig` implementation. We will help you on that of course.

**Comment by ezimuel** [comment]
Starting from ver. [0.6.0](https://github.com/theodo-group/LLPhant/tree/0.6.0) we changed the return of the `generateStreamOfText()` function. Now it returns a PSR-7 [StreamInterface](https://www.php-fig.org/psr/psr-7/#34-psrhttpmessagestreaminterface) object that doesn't implement the Iterator feature, that means you cannot `foreach`. You can retrieve the result with the `getContents()` method as follows:

```php
$chat = new OpenAIChat($config);
$result = $chat->generateStreamOfText('good morning');
echo $result->getContents(); // Good morning! How can I assist you today?
```
