### ISSUE TITLE
Add a feature to store the vectors to MySQL Database and using from it

### ISSUE THREAD

**Issue by raihan-js** [theodo-group/LLPhant#86]

**Comment by MaximeThoonsen** [comment]
Hey @raihan-js,
I don't think MySQL is super ready yet. Do you have any documentation that say otherwise?

**Comment by raihan-js** [comment]
Hi Maxime!
I have built something that directly converts DB data into vector stores. I'm currently working to create a class that does it. I'll surely contribute!
