### ISSUE TITLE
[Feature] - Add ChromaDB support for Vector Storage

### ISSUE THREAD

**Issue by ErroneousBosch** [theodo-group/LLPhant#88]
ChromaDB is seeing growing use for vector storage, especially for self-hosted. It would be nice to see an integrated option to use it. It unfortunately only has Python and JS clients: https://docs.trychroma.com/reference/Client

There is a package for PHP for using it already, which could in theory be used already: https://github.com/CodeWithKyrian/chromadb-php

**Comment by MaximeThoonsen** [comment]
hey @ErroneousBosch,
Good idea ! Do you want to submit a PR?

**Comment by f-lombardo** [comment]
Hey @MaximeThoonsen , I'd like to try to create an integration with ChromaDB. Do you think that adding a dependency to `odewithkyrian/chromadb-php` would be OK?

**Comment by MaximeThoonsen** [comment]
hey @f-lombardo ,
For now I add this kind of specific dependencies  in the "suggest" section. So we can keep it light and avoid a dependencies hell.
Sounds good to you?

**Comment by f-lombardo** [comment]
It seems a good option, let's try

**Comment by f-lombardo** [comment]
Hey @MaximeThoonsen , maybe this issue could be closed.

**Comment by MaximeThoonsen** [comment]
@f-lombardo yes!
