### ISSUE TITLE
answerQuestionStream function in Question Answering class returns a string. Expected stream interface

### ISSUE THREAD

**Issue by adamanis** [theodo-group/LLPhant#89]
Version: 0.6.2

Currently the answerQuestionStream function in Question Answering Class has string as its return type declaration.

<img width="635" alt="image" src="https://github.com/theodo-group/LLPhant/assets/30252456/97302b12-dde6-4686-b1ef-b24c3cf42d88">

Php coerces the stream interface object returned from generateStreamOfText function to type string

**Comment by MaximeThoonsen** [comment]
Hey @adamanis ,
Thanks for having spotted this. I'll have a look.

**Comment by MaximeThoonsen** [comment]
Hey @adamanis and @BoweFrankema . I just fixed it in the last version.

https://github.com/theodo-group/LLPhant/pull/108

**Comment by BoweFrankema** [comment]
Awesome thank you Maxime!
