### ISSUE TITLE
[Bug] Handle functions without parameters correctly

### ISSUE THREAD

**Issue by vijaythecoder** [theodo-group/LLPhant#95]
I found a bug in the LLPhant PHP package. It's about how it deals with functions that don't take any parameters. 

For example, I have a class called `SendNotification` that looks like this:
```php
namespace App\Tools;

class SendNotification
{
    /**
     * Send Confirmation to the Slack
     */
    public function sendNotificationToSlack(): void
    {
        echo 'Sending Notification....';
    }
}
```

When the package tries to make an object schema for the `sendNotificationToSlack` function, it puts in an empty array for parameters like this:

```php
"tools" => array:1 [
    0 => array:2 [
      "type" => "function"
      "function" => array:3 [
        "name" => "sendNotificationToSlack"
        "description" => "Send Confirmation to the Slack"
        "parameters" => array:3 [
          "type" => "object"
          "properties" => []
          "required" => []
        ]
      ]
    ]
  ]
```

This causes an error with OpenAI, giving me this message:
`OpenAI\Exceptions\ErrorException: Invalid schema for function 'sendNotificationToSlack': [] is not of type 'object'. in file vendor/openai-php/client/src/Transporters/HttpTransporter.php on line 132`

Parameters can be optional as per the [documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools)

### Expected format of the Tool is 
```
"tools" => array:1 [
    0 => array:2 [
      "type" => "function"
      "function" => array:3 [
        "name" => "sendNotificationToSlack"
        "description" => "Send Confirmation to the Slack"
      ]
    ]
  ]
```

**Comment by MaximeThoonsen** [comment]
Hey @vijaythecoder . Thanks to have spotted this one. I'll have a look at it. Feel free to suggest a fix if you have one, I have a busy month 🙈.

**Comment by MaximeThoonsen** [comment]
hey @vijaythecoder ,
I pushed a fix in the last version. Tell me if it is working correctly on your side please.

**Comment by vijaythecoder** [comment]
Hey sorry, couldn't get back to you in time. Thanks for posting the fix. I will test it and let you know soon. I will try to contribute if I can. Great package though!
