### ISSUE TITLE
Improvment : How to use it inside LLphant

### ISSUE THREAD

**Issue by ClicShopping** [theodo-group/LLPhant#97]
Inside the document you have :

To use Ollama, you can just specify the model to use using the OllamaConfig object and pass it to the OllamaChat.

$config = new OllamaConfig();
$config->model = 'llama2';
$chat = new OllamaChat($config);

I do not see inside LLphant Ollama class. Could update the documentation for clarification to use it or an example. 

Or maybe I miss something.

Thank you

**Comment by MaximeThoonsen** [comment]
Hey @ClicShopping. What do you mean you don't see the Ollama class? 
It doesn't exist but you don't need one. You should use `OllamaChat` class.
Why did you want to have a Ollama class?

**Comment by ClicShopping** [comment]
Hello @MaximeThoonsen 
I ask because when I install LLphant I do not these class below (mistral, ollama ...) . Just GPT4Turbo.php
https://github.com/theodo-group/LLPhant/tree/main/src/Chat
Just a question could add gpt-3.5-turbo-16k  to manage the big document ?
Tk

**Comment by MaximeThoonsen** [comment]
Hey @ClicShopping , you can change the model name in the OpenAI class.
It is the `model` field which is public so you can put any OpenAI model.

Is that good for you?

I may add other class because it's true its convenient to use :)
